# Eureka Client Configuration
eureka:
  client:
    fetchRegistry: true
    registerWithEureka: true
    serviceUrl:
      defaultZone: ${EUREKA.SERVER.HOST:http://localhost:8761/eureka}
  instance:
    leaseRenewalIntervalInSeconds: 2
    leaseExpirationDurationInSeconds: 2

# Enable Actuator config prometheus grafana loki
management:
  endpoints:
    web:
      exposure:
        include: '*'
        base-path: /actuator
  tracing:
    sampling:
      probability: 1.0

# Logging Configuration
logging:
  level:
    org:
      springframework:
        web: INFO # ALL, INFO, ERROR
  pattern:
    level: '%5p [${spring.application.name},%X{traceId:-},%X{spanId:-}]'
