# Eureka Client Configuration
eureka:
  client:
    fetchRegistry: true
    registerWithEureka: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
  instance:
    leaseRenewalIntervalInSeconds: 2
    leaseExpirationDurationInSeconds: 2

# Enable Actuator
management:
  endpoints:
    web:
      exposure:
        include: '*'
        base-path: /actuator