server:
  port: ${CUSTOM.SERVER.PORT:9990}

# Mongo Configuration
spring:
  data:
    mongodb:
      uri: mongodb://mitocode:pasw@localhost:27017/bd-mitocode-ms?authSource=admin
#  kafka:
#    consumer:
#      properties:
#        spring:
#          kafka:
#            consumer:
#              value-deserializer: org.springframework.kafka.support.serializer.ErrorHandlingDeserializer
#              spring.kafka.consumer.properties.spring.kafka.consumer.value-deserializer.delegate.class: org.springframework.kafka.support.serializer.JsonDeserializer
#              spring.kafka.consumer.properties.spring.kafka.consumer.value-deserializer.delegate.trusted.packages: "com.mitocode.generic, java.util, java.lang"

# Kafka Parameters
kafka:
  mitocode:
    server: 127.0.0.1
    port: 9092
    topicName: mitocode