server:
  port: 9020

# Spring Cloud Gateway Router
spring:
  cloud:
    gateway:
      routes:
        - id: licencia-service-route
          uri: lb://licencia-service
          predicates:
            - Path=/api/licencia-service/**
          filters:
            - StripPrefix=2
            - LicenciaServiceFilter=X-Tracking-ID,tracking-value-xyz


mitocode:
  security:
    key: cb5a5e83a031e8bdbee887001e4dcd202d5bff8402921506c489ed633be3460e