server:
  port: 9010
  servlet:
    context-path: /gestor-licencias-api


spring:
  # configuración de Base de datos ORACLE
  datasource:
    url: jdbc:oracle:thin:@//localhost:1521/xe
    username: mitocode
    password: '{cipher}ab6cee2558815e45fad14ce6918927bb1c447ca571558a06dfe0a6aa82783777'
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
    show-sql: true
  # Spring securiti - Autenticación con Github
  security:
    oauth2:
      client:
        registration:
          github:
            client-id: Ov23liA2Y7nETyF4E9po
            client-secret: 3387ebffd76baba8e093831ba1089fe6e41bb569

# Swagger - OpenApi
springdoc:
  api-docs:
    enabled: true
    path: /api-docs
  swagger-ui:
    enabled: true
    path: /swagger-ui.html



  